---
language: php

sudo: false

services:
  - mysql

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

branches:
  only:
    - master

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
  slack:
    secure: Gxa5PJc/WCjmKcmz6yBhRTe3p26pNkKvag+0LtL3u9CjmaSsnnvP5kHzOWpkYufbmtN7C7pLlwZHusDKXcXigP/zd1guo0lJ7lFfBUezOs1jUkqesmgP2+TPD+VeLoVzQRnZTb8knkEf/EW74zQxVu35flMLGIwZBYFUzZpd5yI=

install: travis_retry composer install --no-interaction --no-progress --prefer-dist

before_script:
  - mkdir -p build/logs
  - mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';"
  - mysql -e 'create database `OpenBuildings/shipping`;'
  - mysql OpenBuildings/shipping < tests/test_data/structure.sql

script:
  - vendor/bin/phpunit --stderr --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
