--- 
language: php

php:
  - 5.4

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  - mysql -e 'create database `test-shipping`;'
  - mysql test-shipping < tests/test_data/structure.sql

after_script:
  - php vendor/bin/coveralls -v